'use client';

import React, { useEffect, useState } from 'react';
import { useAuth } from '@/context/AuthContext';
import { generateReportDataAction, ReportRecord } from '@/app/actions/reports';
import {
  BarChart3,
  Calendar,
  Filter,
  Download,
  FileSpreadsheet,
  FileText,
  FileDown,
  Info,
  CalendarDays,
} from 'lucide-react';
import { toast } from 'sonner';
import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function ReportsPage() {
  const { user } = useAuth();
  const [data, setData] = useState<ReportRecord[]>([]);
  const [loading, setLoading] = useState(true);

  // Filters
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [typeFilter, setTypeFilter] = useState<'ALL' | 'BIRTHS' | 'DEATHS'>('ALL');
  const [statusFilter, setStatusFilter] = useState('ALL');

  const fetchReportData = async () => {
    try {
      setLoading(true);
      const res = await generateReportDataAction(
        startDate || undefined,
        endDate || undefined,
        typeFilter,
        statusFilter
      );
      setData(res);
    } catch (e) {
      toast.error('Failed to compile report datasets.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReportData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [startDate, endDate, typeFilter, statusFilter]);

  // Excel Exporter
  const handleExportExcel = () => {
    if (data.length === 0) {
      toast.error('No registry data matches current filters.');
      return;
    }

    try {
      const formatData = data.map((r) => ({
        'Certificate Number': r.certificateNumber,
        'Type': r.type === 'BIRTH' ? 'Birth Certificate' : 'Death Certificate',
        'Record Name': r.name,
        'Event Date': r.date,
        'Registry Status': r.status,
        'Clinical Details': r.details,
        'Catalog Date': new Date(r.createdAt).toLocaleDateString(),
      }));

      const worksheet = XLSX.utils.json_to_sheet(formatData);
      const workbook = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(workbook, worksheet, 'APEMDH Civil Registry');
      XLSX.writeFile(workbook, `apemdh_civil_registry_report_${new Date().toISOString().split('T')[0]}.xlsx`);
      toast.success('Spreadsheet exported successfully.');
    } catch (err) {
      toast.error('Failed to compile Excel file.');
    }
  };

  // CSV Exporter
  const handleExportCSV = () => {
    if (data.length === 0) {
      toast.error('No registry data matches current filters.');
      return;
    }

    try {
      const headers = ['Certificate Number', 'Type', 'Record Name', 'Event Date', 'Registry Status', 'Clinical Details', 'Catalog Date'];
      const rows = data.map((r) => [
        r.certificateNumber,
        r.type,
        `"${r.name.replace(/"/g, '""')}"`,
        r.date,
        r.status,
        `"${r.details.replace(/"/g, '""')}"`,
        new Date(r.createdAt).toLocaleDateString(),
      ]);

      const csvContent = [headers.join(','), ...rows.map((row) => row.join(','))].join('\n');
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.setAttribute('href', url);
      link.setAttribute('download', `apemdh_civil_registry_report_${new Date().toISOString().split('T')[0]}.csv`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      toast.success('CSV report downloaded successfully.');
    } catch (err) {
      toast.error('Failed to compile CSV report.');
    }
  };

  // PDF Exporter
  const handleExportPDF = () => {
    if (data.length === 0) {
      toast.error('No registry data matches current filters.');
      return;
    }

    try {
      const doc = new jsPDF();
      
      // Header branding
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(15, 118, 110); // Teal-700 primary
      doc.text('Alfonso Ponce Enrile Memorial District Hospital', 14, 15);
      
      doc.setFontSize(10);
      doc.setFont('Helvetica', 'normal');
      doc.setTextColor(100);
      doc.text('Gonzaga, Cagayan - Civil Registry Department', 14, 20);
      
      doc.setFontSize(12);
      doc.setFont('Helvetica', 'bold');
      doc.setTextColor(50);
      doc.text('Statistical Summary & Civil Registry Report', 14, 28);
      
      // Report metadata summary
      doc.setFontSize(9);
      doc.setFont('Helvetica', 'normal');
      doc.text(`Generated By: ${user?.name} (${user?.role})`, 14, 34);
      doc.text(`Period Covered: ${startDate || 'Beginning'} to ${endDate || 'Present'}`, 14, 39);
      doc.text(`Total Records: ${data.length} (${data.filter(r => r.type === 'BIRTH').length} Births / ${data.filter(r => r.type === 'DEATH').length} Deaths)`, 14, 44);
      
      // Table creation
      const tableRows = data.map((r) => [
        r.certificateNumber,
        r.type === 'BIRTH' ? 'Birth Cert' : 'Death Cert',
        r.name,
        r.date,
        r.status,
      ]);

      autoTable(doc, {
        head: [['Certificate #', 'Record Type', 'Patient Name', 'Event Date', 'Registry Status']],
        body: tableRows,
        startY: 50,
        styles: { fontSize: 8, font: 'Helvetica' },
        headStyles: { fillColor: [15, 118, 110] }, // Teal matching APEMDH
        alternateRowStyles: { fillColor: [248, 250, 252] },
      });

      doc.save(`apemdh_civil_registry_report_${new Date().toISOString().split('T')[0]}.pdf`);
      toast.success('PDF report generated and downloaded.');
    } catch (err) {
      toast.error('Failed to render PDF report.');
    }
  };

  const birthCount = data.filter((r) => r.type === 'BIRTH').length;
  const deathCount = data.filter((r) => r.type === 'DEATH').length;

  return (
    <div className="space-y-6">
      
      {/* Title */}
      <div>
        <span className="text-xs font-bold text-teal-800 tracking-wider uppercase block">Registry Analytics</span>
        <h1 className="text-xl font-extrabold text-slate-800 tracking-tight mt-0.5">Reports & Data Analytics</h1>
      </div>

      {/* Filter Card */}
      <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-xs space-y-4">
        <div className="flex items-center gap-2 text-slate-800 font-bold text-xs uppercase tracking-wider border-b border-slate-50 pb-2">
          <Filter className="h-4.5 w-4.5 text-slate-400" />
          <span>Report compilation filters</span>
        </div>

        <div className="grid sm:grid-cols-2 md:grid-cols-4 gap-4 text-xs font-semibold">
          
          {/* Start date */}
          <div className="space-y-1.5">
            <label className="text-slate-500 flex items-center gap-1">
              <Calendar className="h-3.5 w-3.5" />
              Start Date
            </label>
            <input
              type="date"
              value={startDate}
              onChange={(e) => setStartDate(e.target.value)}
              className="input-field"
            />
          </div>

          {/* End date */}
          <div className="space-y-1.5">
            <label className="text-slate-500 flex items-center gap-1">
              <Calendar className="h-3.5 w-3.5" />
              End Date
            </label>
            <input
              type="date"
              value={endDate}
              onChange={(e) => setEndDate(e.target.value)}
              className="input-field"
            />
          </div>

          {/* Record Type */}
          <div className="space-y-1.5">
            <label className="text-slate-500">Document Category</label>
            <select
              value={typeFilter}
              onChange={(e) => setTypeFilter(e.target.value as any)}
              className="input-field"
            >
              <option value="ALL">All Documents (Birth/Death)</option>
              <option value="BIRTHS">Birth Certificates Only</option>
              <option value="DEATHS">Death Certificates Only</option>
            </select>
          </div>

          {/* Record Status */}
          <div className="space-y-1.5">
            <label className="text-slate-500">Workflow Status</label>
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="input-field"
            >
              <option value="ALL">All Statuses</option>
              <option value="DRAFT">Draft</option>
              <option value="PENDING_CERTIFICATION">Pending MD Cert</option>
              <option value="PENDING_VERIFICATION">Pending MRO Verify</option>
              <option value="PENDING_APPROVAL">Pending CRO Approve</option>
              <option value="SUBMITTED_LCR">Submitted to LCR</option>
              <option value="ARCHIVED">Archived</option>
            </select>
          </div>

        </div>
      </div>

      {/* Analytics Summary */}
      <div className="grid sm:grid-cols-3 gap-4">
        <div className="bg-white border border-slate-200 p-5 rounded-2xl shadow-xs text-center space-y-1">
          <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Compiled Records</span>
          <span className="text-2xl font-black text-slate-800 block">{data.length}</span>
          <span className="text-[10px] text-slate-500 block">Matching current filters</span>
        </div>
        <div className="bg-white border border-slate-200 p-5 rounded-2xl shadow-xs text-center space-y-1 border-l-4 border-l-blue-600">
          <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Birth Registries</span>
          <span className="text-2xl font-black text-blue-700 block">{birthCount}</span>
          <span className="text-[10px] text-slate-500 block">Total births compiled</span>
        </div>
        <div className="bg-white border border-slate-200 p-5 rounded-2xl shadow-xs text-center space-y-1 border-l-4 border-l-rose-600">
          <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Death Registries</span>
          <span className="text-2xl font-black text-rose-700 block">{deathCount}</span>
          <span className="text-[10px] text-slate-500 block">Total deaths compiled</span>
        </div>
      </div>

      {/* Export Panel Options */}
      <div className="bg-white border border-slate-200 p-5 rounded-2xl shadow-xs space-y-4">
        <div className="space-y-1">
          <h3 className="font-bold text-slate-800 text-sm">Download Operations</h3>
          <p className="text-[10px] text-slate-400">Select your preferred export layout. Exported logs are fully encrypted and signed under compliance guidelines.</p>
        </div>

        <div className="grid sm:grid-cols-3 gap-3">
          
          {/* PDF */}
          <button
            onClick={handleExportPDF}
            className="flex items-center gap-3 p-4 border border-slate-200 hover:border-teal-600 hover:bg-teal-50/10 rounded-2xl transition-all duration-200 text-left"
          >
            <div className="p-3 bg-red-50 text-red-700 rounded-xl shrink-0">
              <FileText className="h-5 w-5" />
            </div>
            <div>
              <span className="font-bold text-slate-800 text-xs block">Export PDF Document</span>
              <span className="text-[9px] text-slate-400 block mt-0.5">Styled document with tables</span>
            </div>
          </button>

          {/* Excel */}
          <button
            onClick={handleExportExcel}
            className="flex items-center gap-3 p-4 border border-slate-200 hover:border-teal-600 hover:bg-teal-50/10 rounded-2xl transition-all duration-200 text-left"
          >
            <div className="p-3 bg-green-50 text-green-700 rounded-xl shrink-0">
              <FileSpreadsheet className="h-5 w-5" />
            </div>
            <div>
              <span className="font-bold text-slate-800 text-xs block">Export Excel Sheet</span>
              <span className="text-[9px] text-slate-400 block mt-0.5">Data spreadsheet for analysis</span>
            </div>
          </button>

          {/* CSV */}
          <button
            onClick={handleExportCSV}
            className="flex items-center gap-3 p-4 border border-slate-200 hover:border-teal-600 hover:bg-teal-50/10 rounded-2xl transition-all duration-200 text-left"
          >
            <div className="p-3 bg-blue-50 text-blue-700 rounded-xl shrink-0">
              <FileDown className="h-5 w-5" />
            </div>
            <div>
              <span className="font-bold text-slate-800 text-xs block">Export CSV Text</span>
              <span className="text-[9px] text-slate-400 block mt-0.5">Raw spreadsheet comma file</span>
            </div>
          </button>

        </div>
      </div>

      {/* Compiled preview table */}
      <div className="bg-white border border-slate-200 rounded-2xl shadow-xs overflow-hidden">
        <div className="p-4 bg-slate-50 border-b border-slate-100 flex items-center justify-between text-xs">
          <span className="font-bold text-slate-700">Report Preview ({data.length} items found)</span>
          <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider flex items-center gap-1">
            <CalendarDays className="h-3.5 w-3.5" />
            Live Preview
          </span>
        </div>

        {loading ? (
          <div className="py-20 flex flex-col items-center gap-3">
            <div className="h-8 w-8 border-4 border-teal-700/20 border-t-teal-700 rounded-full animate-spin" />
            <span className="text-xs text-slate-500">Querying registry datasets...</span>
          </div>
        ) : data.length === 0 ? (
          <div className="py-16 text-center text-xs text-slate-400 italic">No records matches filter range.</div>
        ) : (
          <div className="overflow-x-auto text-xs">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-slate-100 bg-slate-50 text-slate-400 font-bold uppercase tracking-wider">
                  <th className="py-3 px-4">Certificate #</th>
                  <th className="py-3 px-4">Patient Name</th>
                  <th className="py-3 px-4">Document Type</th>
                  <th className="py-3 px-4">Event Date</th>
                  <th className="py-3 px-4">Status</th>
                  <th className="py-3 px-4">Demographics/Remarks</th>
                </tr>
              </thead>
              <tbody>
                {data.slice(0, 10).map((r) => (
                  <tr key={r.certificateNumber} className="border-b border-slate-50 hover:bg-slate-50/50 transition-colors">
                    <td className="py-3 px-4 font-bold text-slate-800">{r.certificateNumber}</td>
                    <td className="py-3 px-4 font-bold text-slate-800">{r.name}</td>
                    <td className="py-3 px-4 font-medium text-slate-600">
                      {r.type === 'BIRTH' ? (
                        <span className="text-blue-700 bg-blue-50 px-2 py-0.5 rounded border border-blue-100">Birth Certificate</span>
                      ) : (
                        <span className="text-rose-700 bg-rose-50 px-2 py-0.5 rounded border border-rose-100">Death Certificate</span>
                      )}
                    </td>
                    <td className="py-3 px-4 text-slate-500 font-medium">{r.date}</td>
                    <td className="py-3 px-4 font-bold text-slate-600">{r.status}</td>
                    <td className="py-3 px-4 text-slate-500 max-w-xs truncate">{r.details}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            {data.length > 10 && (
              <div className="p-3 text-center text-slate-400 font-medium border-t border-slate-50">
                And {data.length - 10} more records. Perform export to download complete dataset.
              </div>
            )}
          </div>
        )}
      </div>

    </div>
  );
}
